### ISSUE TITLE
roadmap for go-cli

### ISSUE THREAD

**Issue by jryannel** [apigear-io/cli#1]
- [x] same api module format is supported
- [x] same solution format is supported
- [x] same scenario format is supported
- [x] monitoring works with ts generated code
- [x] simulation works with ts generated code
- [x] ported go template
- [x] ported python template
- [x] ported UE template
- [x] ported c++ template
- [x] ported typescript template
- [x] ported QtC++ template
- [x] cli is fully documented
- [x] template package management is fully supported
- [x] filters are documented
- [x] template lang is documented
- [x] enum members rename to values
- [x] change templates folder name to documents as rules defines documents (or rename documents in rules to templates)
- [x] rename inputs back to params and output back to return
- [x] ensure raw documents are directly copied and not looked up by the template engine
